export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPage';
export { DashboardPage } from './DashboardPage';
export { ExercisePage } from './ExercisePage';
export { SettingsPage } from './SettingsPage';
export { ConsentPendingPage } from './ConsentPendingPage';
export { TeacherDashboardPage } from './TeacherDashboardPage';
export { TeacherStudentDetailPage } from './TeacherStudentDetailPage';
export { TeacherExercisesPage } from './TeacherExercisesPage';
